# file      : tests/manifest-serializer/buildfile
# copyright : Copyright (c) 2014-2019 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

import mods = libbutl.bash%bash{manifest-serializer}

exe{driver}: in{driver} $mods testscript
