# file      : libbutl/buildfile
# license   : MIT; see accompanying LICENSE file

import libs = libbutl%lib{butl}

./: bash{$path.base($path.base(*.bash.in))}

bash{utility}: in{utility}

bash{manifest-parser}: in{manifest-parser} bash{utility}
bash{manifest-parser}: exe{manifest}: install = true

bash{manifest-serializer}: in{manifest-serializer} bash{utility}
bash{manifest-serializer}: exe{manifest}: install = true

bash{standard-version}: in{standard-version} bash{utility}
bash{standard-version}: exe{standard-version}: install = true

exe{manifest}:         cxx{manifest}         $libs
exe{standard-version}: cxx{standard-version} $libs

# Install our binding support executables next to the modules.
#
exe{*}: install = bin/libbutl/
